kind: pipeline
type: docker
name: pipeline

clone:
  depth: 1

steps:
# 恢复node_modules
- name: restore-cache-node_modules
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./node_modules

- name: Preparation
  image: node:12.22.10
  pull: if-not-exists
  commands:
  - yarn config set registry https://registry.npmmirror.com/
  - yarn install

# 建立缓存node_modules
- name: rebuild-cache-node_modules
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./node_modules

# 恢复dist
# - name: restore-cache-dist
#   image: drillster/drone-volume-cache
#   pull: if-not-exists
#   volumes:
#   - name: cache
#     path: /cache
#   settings:
#     restore: true
#     mount:
#     - ./.mfsu-production

- name: Build
  image: node:12.22.10
  pull: if-not-exists
  commands:
  - yarn build

# 建立缓存dist
# - name: rebuild-cache
#   image: drillster/drone-volume-cache
#   pull: if-not-exists
#   volumes:
#   - name: cache
#     path: /cache
#   settings:
#     rebuild: true
#     mount:
#     - ./.mfsu-production

- name: Deploy
  image: appleboy/drone-scp
  pull: if-not-exists
  settings:
    host:
      from_secret: host
    username:
      from_secret: username
    password:
      from_secret: password
    port:
      from_secret: port
    target: /www/wwwroot/self_admin_react
    source: ./build
  when:
    branch:
    - dev

volumes:
  - name: cache
    host:
      path: /cache/drone/self_admin_react
